/*1*/
DECLARE
    V_COCHE COCHE%ROWTYPE;
    V_MATRICULA COCHE.MATRICULA%TYPE := '&MATRICULA'; 
BEGIN
    SELECT * INTO V_COCHE FROM COCHE
    WHERE MATRICULA = V_MATRICULA;
    DBMS_OUTPUT.PUT_LINE('EL COCHE QUE TIENE DE MATRICULA '|| V_COCHE.MATRICULA ||  ' ES UN '|| V_COCHE.ID_MODELO || ' Y VALE: ' || V_COCHE.PRECIO_COMPRA);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NEL');
END;
/
/*2*/
DECLARE
    V_MATRICULA VENDE.MATRICULA%TYPE := '&MATRICULA';
    V_DUMMY NUMBER;
BEGIN
    SELECT 1 INTO V_DUMMY
    FROM VENDE
    WHERE MATRICULA = V_MATRICULA;

    DBMS_OUTPUT.PUT_LINE('VENDIDO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ESTA VENDIDO');
END;
/
/*3*/
DECLARE
    V_DNI   VENDE.DNI_CLIENTE%TYPE := '&DNI';
    
    CURSOR C_VENTAS IS
        SELECT MATRICULA, FECHA, PRECIO
        FROM VENDE
        WHERE DNI_CLIENTE = V_DNI;
        
    V_MATRICULA VENDE.MATRICULA%TYPE;
    V_FECHA     VENDE.FECHA%TYPE;
    V_PRECIO    VENDE.PRECIO%TYPE;
BEGIN
    OPEN C_VENTAS;
    LOOP
        FETCH C_VENTAS INTO V_MATRICULA, V_FECHA, V_PRECIO;
        EXIT WHEN C_VENTAS%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('MATRICULA: '||V_MATRICULA||' | FECHA: '||V_FECHA||' | PRECIO: '||V_PRECIO);
    END LOOP;
    CLOSE C_VENTAS;
END;
/

/*4*/
CREATE OR REPLACE TRIGGER VERPRECIOCOMPRA
BEFORE INSERT ON COCHE
FOR EACH ROW
BEGIN
    IF :NEW.PRECIO_COMPRA IS NULL OR :NEW.PRECIO_COMPRA <=0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'ESE PRECIO DE COMPRA NO ESTA PERMITIDO');
    END IF;
END;
/
INSERT INTO COCHE (MATRICULA, ID_MODELO, PRECIO_COMPRA) VALUES ('1939EVA', 0, 0);
/
/*5*/
DECLARE
    V_MATRICULA COCHE.MATRICULA%TYPE := '&MATRICULA';
    V_PRECIO_COMPRA COCHE.PRECIO_COMPRA%TYPE;
    V_PRECIO_NUEVO NUMBER;
BEGIN
    SELECT PRECIO_COMPRA
    INTO V_PRECIO_COMPRA
    FROM COCHE
    WHERE MATRICULA = V_MATRICULA;

    V_PRECIO_NUEVO := V_PRECIO_COMPRA * 1.10;

    UPDATE COCHE
    SET PRECIO_COMPRA = V_PRECIO_NUEVO
    WHERE MATRICULA = V_MATRICULA;

    DBMS_OUTPUT.PUT_LINE('ANTES: ' || V_PRECIO_COMPRA);
    DBMS_OUTPUT.PUT_LINE('DESPUÉS: ' || V_PRECIO_NUEVO);
END;
/

/*6*/
DECLARE
    CURSOR C_MARCAS IS 
        SELECT ID_MARCA, MARCA FROM MARCAS_COCHE ORDER BY ID_MARCA;

    V_ID   MARCAS_COCHE.ID_MARCA%TYPE;
    V_NOM  MARCAS_COCHE.MARCA%TYPE;
    V_TOTAL NUMBER;
BEGIN
    OPEN C_MARCAS;
    LOOP
        FETCH C_MARCAS INTO V_ID, V_NOM;
        EXIT WHEN C_MARCAS%NOTFOUND;

        SELECT COUNT(*)
        INTO V_TOTAL
        FROM COCHE CO
        JOIN MODELO_COCHE MO ON CO.ID_MODELO = MO.ID_MODELO
        WHERE MO.ID_MARCA = V_ID;

        DBMS_OUTPUT.PUT_LINE(V_NOM || ': ' || V_TOTAL || ' COCHES');
    END LOOP;

    CLOSE C_MARCAS;
END;
/
/*7*/
DECLARE
    V_ANIOS NUMBER;
BEGIN
    V_ANIOS := &ANIOS;

    FOR R IN (
        SELECT DNI, NOMBRE, ANIO_INCORPORACION
        FROM EMPLEADO
        WHERE EXTRACT(YEAR FROM SYSDATE) - ANIO_INCORPORACION > V_ANIOS
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.NOMBRE || ' - ' || R.DNI);
    END LOOP;
END;

/*8*/
DECLARE
    V_BORRADAS NUMBER;
BEGIN
    DELETE FROM VENDE
    WHERE EXTRACT(YEAR FROM FECHA) < 2017;

    V_BORRADAS := SQL%ROWCOUNT;

    DBMS_OUTPUT.PUT_LINE('VENTAS BORRADAS: ' || V_BORRADAS);
END;
/
/*9*/
DECLARE
    V_DNI   CLIENTE.DNI%TYPE;
    V_NOM   CLIENTE.NOMBRE%TYPE;
    V_TEL   CLIENTE.TELEF%TYPE;
    V_EXISTE NUMBER;
BEGIN
    V_DNI := '&DNI';
    V_NOM := '&NOMBRE';
    V_TEL := '&TELEFONO';

    SELECT COUNT(*) INTO V_EXISTE
    FROM CLIENTE
    WHERE DNI = V_DNI;

    IF V_EXISTE = 0 THEN
        INSERT INTO CLIENTE(DNI, NOMBRE, TELEF)
        VALUES(V_DNI, V_NOM, V_TEL);

        DBMS_OUTPUT.PUT_LINE('CLIENTE INSERTADO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ESE YA EXISTE');
    END IF;
END;
/
/*10*/
DECLARE
    CURSOR C_COCHES IS
        SELECT MATRICULA, ID_MODELO
        FROM COCHE
        WHERE PRECIO_COMPRA IS NULL;

    V_MAT COCHE.MATRICULA%TYPE;
    V_MOD COCHE.ID_MODELO%TYPE;
BEGIN
    OPEN C_COCHES;
    LOOP
        FETCH C_COCHES INTO V_MAT, V_MOD;
        EXIT WHEN C_COCHES%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(V_MAT || ' - MODELO: ' || V_MOD);
    END LOOP;
    CLOSE C_COCHES;
END;
/
/*11*/
/*Pedir matrícula y calcular:  
beneficio = precio_venta – precio_compra
Mostrar ambos valores.*/
DECLARE
    V_MATRICULA COCHE.MATRICULA%TYPE := '&MATRICULA';
    V_PRECIO_COMPRA COCHE.PRECIO_COMPRA%TYPE;
    V_PRECIO_VENTA VENDE.PRECIO%TYPE;
    BENEFICIO NUMBER;
BEGIN
    SELECT PRECIO_COMPRA INTO V_PRECIO_COMPRA FROM COCHE
    WHERE MATRICULA = V_MATRICULA;

    SELECT PRECIO INTO V_PRECIO_VENTA FROM VENDE
    WHERE MATRICULA = V_MATRICULA;
    
    BENEFICIO := V_PRECIO_VENTA - V_PRECIO_COMPRA;

    DBMS_OUTPUT.PUT_LINE('PRECIO COMPRA: ' || V_PRECIO_COMPRA);
    DBMS_OUTPUT.PUT_LINE('PRECIO VENTA : ' || V_PRECIO_VENTA);
    DBMS_OUTPUT.PUT_LINE('BENEFICIO    : ' || BENEFICIO);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE ESA MATRÍCULA O NO TIENE VENTA REGISTRADA');
END;
/
/*12*/
DECLARE
    V_MAT COCHE.MATRICULA%TYPE := '&MATRICULA';
BEGIN
    UPDATE VENDE
    SET ID_FORMA_PAGO = 4
    WHERE MATRICULA = V_MAT;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE VENTA CON ESA MATRÍCULA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FORMA DE PAGO ACTUALIZADA');
    END IF;
END;
/
/*13*/
DECLARE
    V_DNI EMPLEADO.DNI%TYPE := '&DNI';
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM VENDE
    WHERE DNI_EMPLEADO = V_DNI;

    DBMS_OUTPUT.PUT_LINE('VENTAS REALIZADAS: ' || V_TOTAL);
END;
/
/*14*/
DECLARE
    V_MATRICULA COCHE.MATRICULA%TYPE := '&MATRICULA';
    V_DUMMY NUMBER;
BEGIN
    SELECT 1 INTO V_DUMMY
    FROM COCHE
    WHERE MATRICULA = V_MATRICULA;

    DBMS_OUTPUT.PUT_LINE(V_MATRICULA || ' EXISTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'EL COCHE ' || V_MATRICULA || ' NO EXISTE');
END;
/
/*15*/
BEGIN
    FOR R IN (
        SELECT C.NOMBRE CLIENTE,E.NOMBRE EMPLEADO, M.MARCA, MO.DESCRIPCION MODELO, V.PRECIO
        FROM VENDE V
        JOIN CLIENTE C ON V.DNI_CLIENTE = C.DNI
        JOIN EMPLEADO E ON V.DNI_EMPLEADO = E.DNI
        JOIN COCHE CO ON V.MATRICULA = CO.MATRICULA
        JOIN MODELO_COCHE MO ON CO.ID_MODELO = MO.ID_MODELO
        JOIN MARCAS_COCHE M ON MO.ID_MARCA = M.ID_MARCA
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.CLIENTE || '-' || R.EMPLEADO || '-' || R.MARCA || '-' || R.MODELO || '-' || R.PRECIO);
    END LOOP;
END;
/
/*16*/
DECLARE
    V_MATRICULA COCHE.MATRICULA%TYPE := '&MATRICULA';
    V_ID_MODELO COCHE.ID_MODELO%TYPE := '&MODELO';
    V_PRECIO_COMPRA COCHE.PRECIO_COMPRA%TYPE := '&PRECIO';
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM COCHE
    WHERE MATRICULA = V_MATRICULA;

    IF V_EXISTE = 0 THEN
        INSERT INTO COCHE(MATRICULA, ID_MODELO, PRECIO_COMPRA)
        VALUES(V_MATRICULA, V_ID_MODELO, V_PRECIO_COMPRA);

        DBMS_OUTPUT.PUT_LINE('COCHE INSERTADO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('COCHE YA EXISTENTE');
    END IF;
END;
/
/*17*/
DECLARE
    V_DNI CLIENTE.DNI%TYPE := '&DNI';
    V_TEL CLIENTE.TELEF%TYPE := '&TELEFONO';
BEGIN
    UPDATE CLIENTE
    SET TELEF = V_TEL
    WHERE DNI = V_DNI;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('EL CLIENTE NO EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('TELÉFONO ACTUALIZADO');
    END IF;
END;
/
/*18*/
DECLARE
    V_MAT COCHE.MATRICULA%TYPE;
    V_PREC COCHE.PRECIO_COMPRA%TYPE;
BEGIN
    SELECT MATRICULA, PRECIO_COMPRA
    INTO V_MAT, V_PREC
    FROM COCHE
    WHERE PRECIO_COMPRA = (SELECT MAX(PRECIO_COMPRA) FROM COCHE);

    DBMS_OUTPUT.PUT_LINE(V_MAT || ' - ' || V_PREC);
END;
/
/*19*/
DECLARE
    V_ID MARCAS_COCHE.ID_MARCA%TYPE := &ID_MARCA;
BEGIN
    FOR R IN (
        SELECT DESCRIPCION
        FROM MODELO_COCHE
        WHERE ID_MARCA = V_ID
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.DESCRIPCION);
    END LOOP;
END;
/
/*20*/
CREATE TABLE log_ventas ( 
id_log NUMBER(3) PRIMARY KEY, 
log VARCHAR2(30) 
);

create or replace trigger tr_log_ventas
after insert on vende
for each row
begin
    insert into log_ventas
    values(sysdate, :new.dni_empleado, :new.dni_cliente, :new.matricula, :new.precio);
end;
/