/*Ejercicio 1. Jose Aranda*/
DECLARE
    V_MATRICULA VENDE.MATRICULA%TYPE:='&MATRICULA'; /*3345GVF*/
    V_ID_FORMA_PAGO VENDE.ID_FORMA_PAGO%type;
    v_precio vende.precio%type;
BEGIN
    SELECT ID_FORMA_PAGO,PRECIO INTO V_ID_FORMA_PAGO,v_precio FROM VENDE
    WHERE MATRICULA=V_MATRICULA;
    DBMS_OUTPUT.PUT_LINE('Matricula: '||V_MATRICULA
    ||' Precio Venta: '||v_precio
    ||' Forma de Pago: '||V_ID_FORMA_PAGO);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE NINGUNA VENTA CON ESA MATRICULA');
END;/*NO ESTA COMPLETO PORQUE ME DABA ERRORES de que si mucha info, que esto, etc...*/
/
/*Ejercicio 2. Jose Aranda*/
/*Ejercicio 1. Jose Aranda*/
DECLARE
    V_MATRICULA VENDE.MATRICULA%TYPE:='&MATRICULA'; /*3345GVF*/
    V_ID_FORMA_PAGO VENDE.ID_FORMA_PAGO%type;
    v_precio vende.precio%type;
BEGIN
    SELECT ID_FORMA_PAGO,PRECIO INTO V_ID_FORMA_PAGO,v_precio FROM VENDE
    WHERE MATRICULA=V_MATRICULA;
    DBMS_OUTPUT.PUT_LINE('Matricula: '||V_MATRICULA
    ||' Precio Venta: '||v_precio
    ||' Forma de Pago: '||V_ID_FORMA_PAGO);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE NINGUNA VENTA CON ESA MATRICULA');
END;/*NO ESTA COMPLETO PORQUE ME DABA ERRORES de que si mucha info, que esto, etc...*/
/
/*Ejercicio 2. Jose Aranda*/
CREATE OR REPLACE PROCEDURE PUESTO_EMPLEADO(V_DNI EMPLEADO.DNI%TYPE:='&dni') /*05678245B*/
IS
    V_NOMBRE EMPLEADO.NOMBRE%TYPE;
    V_ID_PUESTO EMPLEADO.ID_PUESTO%TYPE;
BEGIN
    SELECT NOMBRE,ID_PUESTO INTO V_NOMBRE,V_ID_PUESTO FROM EMPLEADO
    WHERE DNI = V_DNI;
    DBMS_OUTPUT.PUT_LINE('DNI '||V_DNI||' Nombre: '||V_NOMBRE||' Puesto: '||V_ID_PUESTO);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE DNI');
END PUESTO_EMPLEADO;
/

